#spring.cloud.gateway.routes[0].id=EMPLOYEE
#spring.cloud.gateway.routes[0].uri=lb://EMPLOYEE
#spring.cloud.gateway.routes[0].predicates[0]=Path=/employee/**
#spring.cloud.gateway.routes[1].id=Room_Service
#spring.cloud.gateway.routes[1].uri=lb://Room_Service
#spring.cloud.gateway.routes[1].predicates[0]=Path=/room/**
spring.main.web-application-type=reactive

#spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_URI_ISSUER:http://localhost:8080/realms/hotelmanagement}
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_URI_SET:http://localhost:8080/realms/hotelmanagement/protocol/openid-connect/certs}

#aBelow is for Keycloak client of HMT API Gateway
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/hotelmanagement
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/hotelmanagement/protocol/openid-connect/certs
