spring.application.name=KPIChatbot
server.port=8883

#for KPI Chatbot
spring.ai.openai.api-key=YOUR_OPENAI_API_KEY_HERE
spring.ai.openai.model=gpt-3.5-turbo

#for Keyclock Autherntication and authorization
spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8080/realms/hotelmanagement
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/hotelmanagement/protocol/openid-connect/certs
