spring.application.name=Admin
server.port=8884

spring.main.allow-bean-definition-overriding=true
spring.jackson.serialization.fail-on-empty-beans=false

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8080/realms/hotelmanagement
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/hotelmanagement/protocol/openid-connect/certs
